server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.13.203:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: log
          __path__: /logs/my.log

